#pragma once
#include <cstdint>

enum OpCode : uint8_t
{
    OP_CONSTANT = 0,
    OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_MOD, OP_NEG,
    OP_GREATER, OP_LESS, OP_EQUAL,
    OP_NOT,
    OP_JUMP, OP_JUMP_IF_FALSE, OP_LOOP,
    OP_GET_LOCAL,
    OP_SET_LOCAL,
    OP_GET_GLOBAL,
    OP_SET_GLOBAL,
    OP_DEFINE_GLOBAL,

    OP_AND, OP_OR,

    OP_BUILD_ARRAY,
    OP_GET_INDEX,
    OP_SET_INDEX,
    OP_ARRAY_LEN,
    OP_ARRAY_PUSH, OP_POP,

    OP_CALL,

    OP_SET_PROPERTY_WEAK,

    OP_CLASS,
    OP_FIELD,
    OP_METHOD,
    OP_GET_PROPERTY,
    OP_SET_PROPERTY,

    OP_RETURN = 255
};